import type { Course } from './hootup-data'

export type CategoryCourse = Course & {
  subcategory: string
  earlybird?: boolean
  event?: boolean
}

/** 새로운 클래스 세부 필터 (대분류 기준) */
export const newClassesSubcategories = [
  '전체',
  '개발 & IT',
  '커리어 & 머니',
  '디자인 & 크리에이티브',
  '사진 & 영상',
  '드로잉 & 일러스트',
  '운동 & 마음챙김',
  '공예 & 핸드메이드',
  '요리 & 베이킹',
] as const

export type NewClassesSubcategory = (typeof newClassesSubcategories)[number]

/** 새로운 클래스 1페이지 (16강 · 오픈일 최신순) */
export const newClassesCoursesPage1: CategoryCourse[] = [
  {
    id: 'new-claude',
    title: '개발 생산성 10배 올리는 클로드 코드 마스터 과정',
    author: '새벽코딩 제이든・48강・10시간',
    discount: 30,
    origin: 154000,
    final: 107800,
    rating: 4.9,
    reviews: 3480,
    thumb: '/figma/img/cat-claude.png',
    avatar: '/figma/img/avatar-1.png',
    subcategory: '개발 & IT',
    event: true,
  },
  {
    id: 'new-cm2-itjob',
    title: '비전공자의 IT 직무 취업 전략 컨설팅',
    author: '커리어내비 윤・38강・8시간',
    discount: 40,
    origin: 121000,
    final: 72600,
    rating: 4.8,
    reviews: 3120,
    thumb: '/figma/img/cm2-itjob.png',
    avatar: '/figma/img/cm-av-sua.png',
    subcategory: '커리어 & 머니',
    event: true,
  },
  {
    id: 'new-dc-research',
    title: '데이터로 설득하는 UX 리서치 입문 클래스',
    author: '리서처 다인・38강・8시간',
    discount: 25,
    origin: 121000,
    final: 90750,
    rating: 4.6,
    reviews: 1120,
    thumb: '/figma/img/dc-research.png',
    avatar: '/figma/img/cm-av-jin.png',
    subcategory: '디자인 & 크리에이티브',
    earlybird: true,
  },
  {
    id: 'new-pv-shortform',
    title: '클릭을 부르는 숏폼(릴스·쇼츠) 제작 클래스',
    author: '숏폼러 단비・46강・9시간',
    discount: 40,
    origin: 121000,
    final: 72600,
    rating: 4.8,
    reviews: 2940,
    thumb: '/figma/img/pv-shortform.png',
    avatar: '/figma/img/pv-av-4.png',
    subcategory: '사진 & 영상',
    event: true,
  },
  {
    id: 'new-cb-cocktail',
    title: '집에서 즐기는 이비자 무알코올 칵테일 & 시즌 음료',
    author: '믹솔로지 도하・28강・5시간 30분',
    discount: 25,
    origin: 77000,
    final: 57750,
    rating: 4.6,
    reviews: 1340,
    thumb: '/figma/img/cb-cocktail.png',
    avatar: '/figma/img/cb-av-11.png',
    subcategory: '요리 & 베이킹',
    earlybird: true,
  },
  {
    id: 'new-vibe',
    title: 'AI와 함께 일하는 바이브 코딩 실무 완전 가이드',
    author: '바이브코더 케이・40강・8시간',
    discount: 35,
    origin: 132000,
    final: 85800,
    rating: 4.8,
    reviews: 2540,
    thumb: '/figma/img/cat-vibe.png',
    avatar: '/figma/img/avatar-1.png',
    subcategory: '개발 & IT',
    earlybird: true,
  },
  {
    id: 'new-ch-wheel',
    title: '물레로 빚는 첫 나만의 도자기, 라이프 도예',
    author: '흙내음 도원・38강・8시간',
    discount: 30,
    origin: 121000,
    final: 84700,
    rating: 4.7,
    reviews: 1560,
    thumb: '/figma/img/ch-wheel.png',
    avatar: '/figma/img/ch-av-9.png',
    subcategory: '공예 & 핸드메이드',
    earlybird: true,
  },
  {
    id: 'new-cm2-seo',
    title: '검색되는 콘텐츠를 만드는 SEO & 블로그',
    author: '그로스해커 진・34강・7시간',
    discount: 30,
    origin: 99000,
    final: 69300,
    rating: 4.6,
    reviews: 1610,
    thumb: '/figma/img/cm2-seo.png',
    avatar: '/figma/img/cm-av-hari.png',
    subcategory: '커리어 & 머니',
    event: true,
  },
  {
    id: 'new-di-lettering',
    title: '굿즈로 만드는 디지털 레터링 고급 클래스',
    author: '글씨공방 단아・28강・5시간 30분',
    discount: 25,
    origin: 77000,
    final: 57750,
    rating: 4.6,
    reviews: 1600,
    thumb: '/figma/img/di-lettering.png',
    avatar: '/figma/img/di-av-7.png',
    subcategory: '드로잉 & 일러스트',
    event: true,
  },
  {
    id: 'new-dc2-mobile',
    title: '모바일 앱 UI 디자인 실전 예제 프로젝트',
    author: '프로덕트 한별・48강・10시간',
    discount: 30,
    origin: 143000,
    final: 100100,
    rating: 4.7,
    reviews: 1640,
    thumb: '/figma/img/dc2-mobile.png',
    avatar: '/figma/img/cm-av-min.png',
    subcategory: '디자인 & 크리에이티브',
    event: true,
  },
  {
    id: 'new-fm-pilates',
    title: '코어가 단단해지는 매트 필라테스 입문자 코스',
    author: '필라테스 윤서・40강・7시간 30분',
    discount: 30,
    origin: 99000,
    final: 69300,
    rating: 4.7,
    reviews: 1940,
    thumb: '/figma/img/fm-pilates.png',
    avatar: '/figma/img/fm-av-9.png',
    subcategory: '운동 & 마음챙김',
    event: true,
  },
  {
    id: 'new-cursor',
    title: '커서·코파일럿 200% 활용법 및 포트폴리오 프로젝트',
    author: '툴덕후 빈・30강・6시간',
    discount: 20,
    origin: 88000,
    final: 70400,
    rating: 4.6,
    reviews: 1410,
    thumb: '/figma/img/cat-cursor.png',
    avatar: '/figma/img/avatar-2.png',
    subcategory: '개발 & IT',
    earlybird: true,
  },
  {
    id: 'new-cm2-youtube',
    title: '홍보가 필요한 사장님들을 위한 유튜브 채널 기획부터 성장까지',
    author: '마케터 하루・44강・9시간',
    discount: 25,
    origin: 110000,
    final: 82500,
    rating: 4.7,
    reviews: 2180,
    thumb: '/figma/img/cm2-youtube.png',
    avatar: '/figma/img/cm-av-doi.png',
    subcategory: '커리어 & 머니',
    earlybird: true,
  },
  {
    id: 'new-ch-resin',
    title: '눈부시도록 투명하게 빛나는 레진 공예 입문반',
    author: '말랑레진 도이・30강・6시간',
    discount: 25,
    origin: 88000,
    final: 66000,
    rating: 4.7,
    reviews: 1880,
    thumb: '/figma/img/ch-resin.png',
    avatar: '/figma/img/ch-av-7.png',
    subcategory: '공예 & 핸드메이드',
    event: true,
  },
  {
    id: 'new-dc2-c4d',
    title: '시네마4D로 만드는 3D 타이포그래피',
    author: '쓰리디랩 노아・40강・8시간 30분',
    discount: 20,
    origin: 132000,
    final: 105600,
    rating: 4.5,
    reviews: 780,
    thumb: '/figma/img/dc2-c4d.png',
    avatar: '/figma/img/cm-av-sua.png',
    subcategory: '디자인 & 크리에이티브',
    event: true,
  },
  {
    id: 'new-pv-davinci',
    title: '다빈치 리졸브로 배우는 영상 색보정 입문',
    author: '컬러리스트 진・52강・11시간',
    discount: 35,
    origin: 132000,
    final: 85800,
    rating: 4.7,
    reviews: 1880,
    thumb: '/figma/img/pv-davinci.png',
    avatar: '/figma/img/pv-av-5.png',
    subcategory: '사진 & 영상',
    earlybird: true,
  }
]

/** 새로운 클래스 2페이지 (8강) */
export const newClassesCoursesPage2: CategoryCourse[] = [
  {
    id: 'new-di-conti',
    title: '웹툰 작가 도담이 알려주는 웹툰 콘티와 연출의 기본기',
    author: '작가 도담・36강・7시간 30분',
    discount: 20,
    origin: 99000,
    final: 79200,
    rating: 4.6,
    reviews: 1180,
    thumb: '/figma/img/di-conti.png',
    avatar: '/figma/img/di-av-10.png',
    subcategory: '드로잉 & 일러스트',
    event: true,
  },
  {
    id: 'new-cm2-ebook',
    title: '전자책·디지털 상품으로 만드는 패시브 인컴',
    author: '솔로창업 도이・38강・7시간 30분',
    discount: 30,
    origin: 99000,
    final: 69300,
    rating: 4.6,
    reviews: 1820,
    thumb: '/figma/img/cm2-ebook.png',
    avatar: '/figma/img/cm-av-min.png',
    subcategory: '커리어 & 머니',
    event: true,
  },
  {
    id: 'new-fm-stress',
    title: '호흡으로 다스리는 스트레스 관리 명상 클래스',
    author: '마인드풀 정・26강・4시간',
    discount: 25,
    origin: 77000,
    final: 57750,
    rating: 4.7,
    reviews: 2350,
    thumb: '/figma/img/fm-stress.png',
    avatar: '/figma/img/fm-av-7.png',
    subcategory: '운동 & 마음챙김',
    earlybird: true,
  },
  {
    id: 'new-nextjs',
    title: 'Next.js로 완성하는 풀스택 웹앱 프로젝트 마스터 과정',
    author: '새벽코딩 제이든・95강・20시간',
    discount: 45,
    origin: 198000,
    final: 108900,
    rating: 4.8,
    reviews: 1890,
    thumb: '/figma/img/cat2-next.png',
    avatar: '/figma/img/avatar-2.png',
    subcategory: '개발 & IT',
    earlybird: true,
  },
  {
    id: 'new-dc2-sns',
    title: '자영업자를 위한 카드뉴스 & SNS 콘텐츠 디자인',
    author: '콘텐츠공방 라라・30강・6시간',
    discount: 35,
    origin: 88000,
    final: 57200,
    rating: 4.7,
    reviews: 2460,
    thumb: '/figma/img/dc2-sns.png',
    avatar: '/figma/img/cm-av-doi.png',
    subcategory: '디자인 & 크리에이티브',
    earlybird: true,
  },
  {
    id: 'new-cb-vegan',
    title: '지중해식으로 건강하게 즐기는 비건 한 끼',
    author: '채식테이블 보리・34강・7시간',
    discount: 25,
    origin: 88000,
    final: 66000,
    rating: 4.6,
    reviews: 1670,
    thumb: '/figma/img/cb-vegan.png',
    avatar: '/figma/img/cb-av-3.png',
    subcategory: '요리 & 베이킹',
    earlybird: true,
  },
  {
    id: 'new-pv-portrait',
    title: '자연광으로 찍는 인물 사진의 기술 입문 과정',
    author: '포트레이트 하린・40강・8시간',
    discount: 20,
    origin: 99000,
    final: 79200,
    rating: 4.6,
    reviews: 1460,
    thumb: '/figma/img/pv-portrait.png',
    avatar: '/figma/img/pv-av-12.png',
    subcategory: '사진 & 영상',
    event: true,
  },
  {
    id: 'new-di-pencil',
    title: '색연필로 그리는 일상의 작은 것들 : 소품 편',
    author: '색칠하는 다오・30강・6시간',
    discount: 25,
    origin: 88000,
    final: 66000,
    rating: 4.7,
    reviews: 1540,
    thumb: '/figma/img/di-pencil.png',
    avatar: '/figma/img/di-av-9.png',
    subcategory: '드로잉 & 일러스트',
    earlybird: true,
  }
]

export const NEW_CLASSES_TOTAL_PAGES = 2

export const newClassesSubcategoryRoutes: Partial<Record<NewClassesSubcategory, string>> = {
  전체: '/category/new-classes',
}

export function getNewClassesCoursesByPage(page: number): CategoryCourse[] {
  if (page === 2) return newClassesCoursesPage2
  return newClassesCoursesPage1
}

export function getAllNewClassesCourses(): CategoryCourse[] {
  return [...newClassesCoursesPage1, ...newClassesCoursesPage2]
}

export function getNewClassesCoursesBySubcategory(sub: NewClassesSubcategory): CategoryCourse[] {
  if (sub === '전체') return getAllNewClassesCourses()
  return getAllNewClassesCourses().filter((c) => c.subcategory === sub)
}


export type NewClassesDeal = 'earlybird' | 'event'

export const newClassesDealRoutes: Record<NewClassesDeal, string> = {
  earlybird: '/category/new-classes/earlybird',
  event: '/category/new-classes/event',
}

export function getNewClassesCoursesByDeal(deal: NewClassesDeal): CategoryCourse[] {
  if (deal === 'earlybird') return getAllNewClassesCourses().filter((c) => c.earlybird)
  return getAllNewClassesCourses().filter((c) => c.event)
}
