import type { Course } from './hootup-data'

export type CategoryCourse = Course & {
  subcategory: string
  earlybird?: boolean
  event?: boolean
}

/** 베스트 클래스 세부 필터 (대분류 기준) */
export const bestClassesSubcategories = [
  '전체',
  '개발 & IT',
  '커리어 & 머니',
  '디자인 & 크리에이티브',
  '사진 & 영상',
  '드로잉 & 일러스트',
  '운동 & 마음챙김',
  '공예 & 핸드메이드',
  '요리 & 베이킹',
] as const

export type BestClassesSubcategory = (typeof bestClassesSubcategories)[number]

/** 베스트 클래스 1페이지 (16강) */
export const bestClassesCoursesPage1: CategoryCourse[] = [
  {
    id: 'best-htmlcss',
    title: '손에 익히는 HTML/CSS 기초 부트캠프',
    author: '코드랩 현우・60강・12시간 30분',
    discount: 20,
    origin: 77000,
    final: 61600,
    rating: 4.8,
    reviews: 5640,
    thumb: '/figma/img/cat-htmlcss.png',
    avatar: '/figma/img/avatar-1.png',
    subcategory: '개발 & IT',
    earlybird: true,
  },
  {
    id: 'best-cm-insta',
    title: '0원으로 시작하는 인스타 콘텐츠 마케팅',
    author: '마케터 하루・50강・10시간',
    discount: 35,
    origin: 121000,
    final: 78650,
    rating: 4.8,
    reviews: 4210,
    thumb: '/figma/img/cm-insta.png',
    avatar: '/figma/img/cm-av-hari.png',
    subcategory: '커리어 & 머니',
    earlybird: true,
    event: true,
  },
  {
    id: 'best-dc-figma',
    title: '피그마로 완성하는 UX/UI 디자인 입문',
    author: '디자이너 서린・40강・9시간',
    discount: 35,
    origin: 132000,
    final: 85800,
    rating: 4.9,
    reviews: 3820,
    thumb: '/figma/img/dc-figma.png',
    avatar: '/figma/img/cm-av-pm.png',
    subcategory: '디자인 & 크리에이티브',
    earlybird: true,
  },
  {
    id: 'best-pv-smartphone',
    title: '스마트폰 하나로 인생샷 만드는 사진 클래스',
    author: '빛그림 윤도・42강・8시간',
    discount: 35,
    origin: 99000,
    final: 64350,
    rating: 4.8,
    reviews: 4920,
    thumb: '/figma/img/pv-smartphone.png',
    avatar: '/figma/img/pv-av-1.png',
    subcategory: '사진 & 영상',
    earlybird: true,
  },
  {
    id: 'best-di-ipad',
    title: '아이패드로 시작하는 감성 캐릭터 드로잉',
    author: '무지(MOOZI)・28강・6시간',
    discount: 35,
    origin: 99000,
    final: 64350,
    rating: 4.9,
    reviews: 4180,
    thumb: '/figma/img/di-ipad.png',
    avatar: '/figma/img/di-av-1.png',
    subcategory: '드로잉 & 일러스트',
    earlybird: true,
  },
  {
    id: 'best-fm-hometrain',
    title: '14일 홈트 챌린지: 코어부터 차근차근 다지기',
    author: '트레이너 강・28강・5시간',
    discount: 35,
    origin: 88000,
    final: 57200,
    rating: 4.8,
    reviews: 6240,
    thumb: '/figma/img/fm-hometrain.png',
    avatar: '/figma/img/fm-av-1.png',
    subcategory: '운동 & 마음챙김',
    earlybird: true,
    event: true,
  },
  {
    id: 'best-ch-candle',
    title: '향으로 채우는 소이캔들 & 디퓨저 만들기 클래스',
    author: '센트랩・32강・6시간',
    discount: 35,
    origin: 88000,
    final: 57200,
    rating: 4.8,
    reviews: 2560,
    thumb: '/figma/img/ch-candle.png',
    avatar: '/figma/img/ch-av-3.png',
    subcategory: '공예 & 핸드메이드',
    earlybird: true,
    event: true,
  },
  {
    id: 'best-cb-homecook',
    title: '자취생을 위한 실패 없는 한 끼 홈쿡 30',
    author: '키친노트 단・40강・8시간',
    discount: 35,
    origin: 88000,
    final: 57200,
    rating: 4.9,
    reviews: 5410,
    thumb: '/figma/img/cb-homecook.png',
    avatar: '/figma/img/cb-av-5.png',
    subcategory: '요리 & 베이킹',
    earlybird: true,
    event: true,
  },
  {
    id: 'best-js-core',
    title: '실무에서 바로 쓰는 자바스크립트 핵심 완전 정복',
    author: '코드랩 현우・72강・15시간',
    discount: 35,
    origin: 132000,
    final: 85800,
    rating: 4.8,
    reviews: 4760,
    thumb: '/figma/img/cat-js-core.png',
    avatar: '/figma/img/avatar-1.png',
    subcategory: '개발 & IT',
    earlybird: true,
  },
  {
    id: 'best-cm-side',
    title: '직장인 사이드프로젝트로 N잡 만드는 법',
    author: '사이드랩 민・48강・10시간',
    discount: 35,
    origin: 132000,
    final: 85800,
    rating: 4.8,
    reviews: 3890,
    thumb: '/figma/img/cm-side.png',
    avatar: '/figma/img/cm-av-min.png',
    subcategory: '커리어 & 머니',
    earlybird: true,
  },
  {
    id: 'best-dc-ps',
    title: '포토샵 누끼부터 합성까지 한 번에 마스터 클래스',
    author: '리터처 오・44강・9시간',
    discount: 35,
    origin: 99000,
    final: 64350,
    rating: 4.8,
    reviews: 3540,
    thumb: '/figma/img/dc-ps.png',
    avatar: '/figma/img/cm-av-hari.png',
    subcategory: '디자인 & 크리에이티브',
    earlybird: true,
    event: true,
  },
  {
    id: 'best-pv-premiere',
    title: '어도비 프리미어 프로 브이로그 편집 A to Z',
    author: '에디터 한새・64강・13시간',
    discount: 40,
    origin: 143000,
    final: 85800,
    rating: 4.9,
    reviews: 3760,
    thumb: '/figma/img/pv-premiere.png',
    avatar: '/figma/img/pv-av-3.png',
    subcategory: '사진 & 영상',
    earlybird: true,
    event: true,
  },
  {
    id: 'best-di-emoji',
    title: '나만의 캐릭터 디자인부터 이모티콘 출시까지',
    author: '무지(MOOZI)・44강・9시간',
    discount: 40,
    origin: 110000,
    final: 66000,
    rating: 4.9,
    reviews: 3520,
    thumb: '/figma/img/di-emoji.png',
    avatar: '/figma/img/di-av-5.png',
    subcategory: '드로잉 & 일러스트',
    earlybird: true,
    event: true,
  },
  {
    id: 'best-fm-yoga',
    title: '뻣뻣한 몸이 풀리는 14일 모닝 요가 루틴',
    author: '요가하는 미오・30강・5시간 30분',
    discount: 35,
    origin: 88000,
    final: 57200,
    rating: 4.9,
    reviews: 3820,
    thumb: '/figma/img/fm-yoga.png',
    avatar: '/figma/img/fm-av-2.png',
    subcategory: '운동 & 마음챙김',
    earlybird: true,
    event: true,
  },
  {
    id: 'best-ch-leather',
    title: '손끝에서 완성되는 첫 가죽 카드지갑 만들기',
    author: '레더공방 모루・30강・6시간',
    discount: 35,
    origin: 99000,
    final: 64350,
    rating: 4.8,
    reviews: 2340,
    thumb: '/figma/img/ch-leather.png',
    avatar: '/figma/img/ch-av-1.png',
    subcategory: '공예 & 핸드메이드',
    earlybird: true,
    event: true,
  },
  {
    id: 'best-cb-baking',
    title: '아이들과 함께하는 실패 없는 홈베이킹 기초반',
    author: '베이커리 오븐・38강・7시간 30분',
    discount: 35,
    origin: 99000,
    final: 64350,
    rating: 4.8,
    reviews: 3320,
    thumb: '/figma/img/cb-baking.png',
    avatar: '/figma/img/cb-av-6.png',
    subcategory: '요리 & 베이킹',
    earlybird: true,
    event: true,
  }
]

/** 베스트 클래스 2페이지 (8강) */
export const bestClassesCoursesPage2: CategoryCourse[] = [
  {
    id: 'best-webpub',
    title: '제로부터 완성하는 반응형 웹 퍼블리싱 마스터 클래스',
    author: '코드랩 현우・52강・11시간',
    discount: 30,
    origin: 110000,
    final: 77000,
    rating: 4.9,
    reviews: 4128,
    thumb: '/figma/img/cat-webpub.png',
    avatar: '/figma/img/avatar-1.png',
    subcategory: '개발 & IT',
    earlybird: true,
  },
  {
    id: 'best-cm-pm',
    title: '비전공자를 위한 서비스 기획·PM 입문',
    author: 'PM 도윤・64강・13시간',
    discount: 35,
    origin: 165000,
    final: 107250,
    rating: 4.8,
    reviews: 3640,
    thumb: '/figma/img/cm-pm.png',
    avatar: '/figma/img/cm-av-pm.png',
    subcategory: '커리어 & 머니',
    earlybird: true,
  },
  {
    id: 'best-dc2-emoji',
    title: '감성 굿즈를 부르는 이모티콘 일러스트',
    author: '무지(MOOZI)・32강・6시간 30분',
    discount: 25,
    origin: 88000,
    final: 66000,
    rating: 4.8,
    reviews: 3260,
    thumb: '/figma/img/dc2-emoji.png',
    avatar: '/figma/img/cm-av-jin.png',
    subcategory: '디자인 & 크리에이티브',
    earlybird: true,
  },
  {
    id: 'best-pv-vlog',
    title: '브이로그 입문: 일상을 영상으로 남기기',
    author: '에디터 한새・44강・9시간',
    discount: 35,
    origin: 110000,
    final: 71500,
    rating: 4.8,
    reviews: 3380,
    thumb: '/figma/img/pv-vlog.png',
    avatar: '/figma/img/pv-av-2.png',
    subcategory: '사진 & 영상',
    earlybird: true,
  },
  {
    id: 'best-di-procreate',
    title: '프로크리에이트 기초부터 채색까지 한 번에',
    author: '무지(MOOZI)・40강・8시간 30분',
    discount: 30,
    origin: 88000,
    final: 61600,
    rating: 4.8,
    reviews: 3240,
    thumb: '/figma/img/di-procreate.png',
    avatar: '/figma/img/di-av-6.png',
    subcategory: '드로잉 & 일러스트',
    earlybird: true,
  },
  {
    id: 'best-fm-sleep',
    title: '자기 전 5분, 잠이 깊어지는 수면 명상',
    author: '마인드풀 정・28강・4시간 30분',
    discount: 30,
    origin: 77000,
    final: 53900,
    rating: 4.8,
    reviews: 3460,
    thumb: '/figma/img/fm-sleep.png',
    avatar: '/figma/img/fm-av-4.png',
    subcategory: '운동 & 마음챙김',
    earlybird: true,
  },
  {
    id: 'best-ch-knit',
    title: '엄마표 사계절 손뜨개 니트 소품 만들기 기초반',
    author: '뜨개상점 보들・36강・7시간',
    discount: 30,
    origin: 88000,
    final: 61600,
    rating: 4.7,
    reviews: 2180,
    thumb: '/figma/img/ch-knit.png',
    avatar: '/figma/img/ch-av-6.png',
    subcategory: '공예 & 핸드메이드',
    earlybird: true,
  },
  {
    id: 'best-cb-homecafe',
    title: '집에서 즐기는 이탈리아 홈카페 음료 클래스',
    author: '바리스타 라온・36강・7시간',
    discount: 35,
    origin: 88000,
    final: 57200,
    rating: 4.8,
    reviews: 2980,
    thumb: '/figma/img/cb-homecafe.png',
    avatar: '/figma/img/cb-av-7.png',
    subcategory: '요리 & 베이킹',
    earlybird: true,
    event: true,
  }
]

export const BEST_CLASSES_TOTAL_PAGES = 2

export const bestClassesSubcategoryRoutes: Partial<Record<BestClassesSubcategory, string>> = {
  전체: '/category/best-classes',
}

export function getBestClassesCoursesByPage(page: number): CategoryCourse[] {
  if (page === 2) return bestClassesCoursesPage2
  return bestClassesCoursesPage1
}

export function getAllBestClassesCourses(): CategoryCourse[] {
  return [...bestClassesCoursesPage1, ...bestClassesCoursesPage2]
}

export function getBestClassesCoursesBySubcategory(sub: BestClassesSubcategory): CategoryCourse[] {
  if (sub === '전체') return getAllBestClassesCourses()
  return getAllBestClassesCourses().filter((c) => c.subcategory === sub)
}
