import type { Course } from './hootup-data'

const AV1 = '/figma/img/avatar-1.png'
const AV2 = '/figma/img/avatar-2.png'

export type CategoryCourse = Course & {
  subcategory: string
  earlybird?: boolean
  event?: boolean
}

export const devItSubcategories = [
  '전체',
  '웹 퍼블리싱',
  '프론트엔드',
  '백엔드 & 서버',
  '모바일 & 앱 개발',
  '데이터 & AI',
  'AI 개발 도구',
  '노코드 & 자동화',
] as const

export type DevItSubcategory = (typeof devItSubcategories)[number]

/** 개발 & IT 카테고리 1페이지 (Figma 16강) */
export const devItCoursesPage1: CategoryCourse[] = [
  {
    id: 'webpub',
    title: '제로부터 완성하는 반응형 웹 퍼블리싱 마스터 클래스',
    author: '코드랩 현우・52강・11시간',
    discount: 30,
    origin: 110000,
    final: 77000,
    rating: 4.9,
    reviews: 4128,
    thumb: '/figma/img/cat-webpub.png',
    avatar: AV1,
    subcategory: '웹 퍼블리싱',
    earlybird: true,
  },
  {
    id: 'js-core',
    title: '실무에서 바로 쓰는 자바스크립트 핵심 완전 정복',
    author: '코드랩 현우・72강・15시간',
    discount: 35,
    origin: 132000,
    final: 85800,
    rating: 4.8,
    reviews: 4760,
    thumb: '/figma/img/cat-js-core.png',
    avatar: AV1,
    subcategory: '프론트엔드',
    earlybird: true,
  },
  {
    id: 'nodejs',
    title: 'Node.js & Express 서버 개발 입문',
    author: '서버지기 강우・70강・14시간',
    discount: 35,
    origin: 154000,
    final: 100100,
    rating: 4.7,
    reviews: 2240,
    thumb: '/figma/img/cat-nodejs.png',
    avatar: AV2,
    subcategory: '백엔드 & 서버',
    earlybird: true,
  },
  {
    id: 'flutter',
    title: 'Flutter로 만드는 첫 크로스플랫폼 앱',
    author: '앱공방 미르・76강・16시간',
    discount: 35,
    origin: 165000,
    final: 107250,
    rating: 4.7,
    reviews: 1760,
    thumb: '/figma/img/cat-flutter.png',
    avatar: AV1,
    subcategory: '모바일 & 앱 개발',
    earlybird: true,
  },
  {
    id: 'python-data',
    title: '데이터로 인사이트를 캐는 파이썬 데이터 분석 입문',
    author: '데이터한입 수아・54강・11시간',
    discount: 40,
    origin: 121000,
    final: 72600,
    rating: 4.8,
    reviews: 3920,
    thumb: '/figma/img/cat-python.png',
    avatar: AV2,
    subcategory: '데이터 & AI',
    earlybird: true,
    event: true,
  },
  {
    id: 'claude',
    title: '개발 생산성 10배 올리는 클로드 코드 마스터 과정',
    author: '새벽코딩 제이든・48강・10시간',
    discount: 30,
    origin: 154000,
    final: 107800,
    rating: 4.9,
    reviews: 3480,
    thumb: '/figma/img/cat-claude.png',
    avatar: AV1,
    subcategory: 'AI 개발 도구',
    earlybird: true,
  },
  {
    id: 'nocode',
    title: '노코드로 3일 만에 웹사이트 런칭 프로젝트',
    author: '빌더 태오・34강・7시간',
    discount: 40,
    origin: 88000,
    final: 52800,
    rating: 4.7,
    reviews: 2050,
    thumb: '/figma/img/cat-nocode.png',
    avatar: AV2,
    subcategory: '노코드 & 자동화',
    earlybird: true,
    event: true,
  },
  {
    id: 'react',
    title: '포트폴리오까지 끝내는 React 프론트엔드 실전 프로젝트',
    author: '코드랩 현우・88강・18시간',
    discount: 40,
    origin: 165000,
    final: 99000,
    rating: 4.8,
    reviews: 2604,
    thumb: '/figma/img/cat-react.png',
    avatar: AV1,
    subcategory: '프론트엔드',
    earlybird: true,
  },
  {
    id: 'pandas',
    title: '판다스 & 시각화로 배우는 데이터 핸들링',
    author: '데이터한입 수아・46강・9시간',
    discount: 30,
    origin: 99000,
    final: 69300,
    rating: 4.7,
    reviews: 2110,
    thumb: '/figma/img/cat-pandas.png',
    avatar: AV2,
    subcategory: '데이터 & AI',
    earlybird: true,
  },
  {
    id: 'vibe',
    title: 'AI와 함께 일하는 바이브 코딩 실무 완전 가이드',
    author: '바이브코더 케이・40강・8시간',
    discount: 35,
    origin: 132000,
    final: 85800,
    rating: 4.8,
    reviews: 2540,
    thumb: '/figma/img/cat-vibe.png',
    avatar: AV1,
    subcategory: 'AI 개발 도구',
    earlybird: true,
  },
  {
    id: 'js-vanilla',
    title: '바닐라 자바 스크립트로 만드는 인터랙티브 웹',
    author: '코드랩 현우・56강・12시간',
    discount: 30,
    origin: 143000,
    final: 100100,
    rating: 4.7,
    reviews: 2180,
    thumb: '/figma/img/cat-js-vanilla.png',
    avatar: AV1,
    subcategory: '프론트엔드',
    earlybird: true,
  },
  {
    id: 'css',
    title: 'CSS Flex & Grid 레이아웃 완전 정복',
    author: '코드랩 현우・44강・8시간 30분',
    discount: 40,
    origin: 99000,
    final: 59400,
    rating: 4.9,
    reviews: 3210,
    thumb: '/figma/img/cat-css.png',
    avatar: AV1,
    subcategory: '웹 퍼블리싱',
    earlybird: true,
    event: true,
  },
  {
    id: 'htmlcss',
    title: '손에 익히는 HTML/CSS 기초 부트캠프',
    author: '코드랩 현우・60강・12시간 30분',
    discount: 20,
    origin: 77000,
    final: 61600,
    rating: 4.8,
    reviews: 5640,
    thumb: '/figma/img/cat-htmlcss.png',
    avatar: AV1,
    subcategory: '웹 퍼블리싱',
    earlybird: true,
  },
  {
    id: 'automation',
    title: 'AI 업무 자동화: 반복 작업을 없애는 방법 마스터 클래스',
    author: '자동화공방 린・44강・9시간',
    discount: 30,
    origin: 99000,
    final: 69300,
    rating: 4.6,
    reviews: 1730,
    thumb: '/figma/img/cat-automation.png',
    avatar: AV2,
    subcategory: '노코드 & 자동화',
    earlybird: true,
  },
  {
    id: 'pair',
    title: 'AI 페어 프로그래밍으로 일하는 법 마스터 클래스',
    author: '페어업 도현・36강・7시간',
    discount: 25,
    origin: 110000,
    final: 82500,
    rating: 4.7,
    reviews: 1620,
    thumb: '/figma/img/cat-pair.png',
    avatar: AV1,
    subcategory: 'AI 개발 도구',
    earlybird: true,
  },
  {
    id: 'cursor',
    title: '커서·코파일럿 200% 활용법 및 포트폴리오 프로젝트',
    author: '툴덕후 빈・30강・6시간',
    discount: 20,
    origin: 88000,
    final: 70400,
    rating: 4.6,
    reviews: 1410,
    thumb: '/figma/img/cat-cursor.png',
    avatar: AV2,
    subcategory: 'AI 개발 도구',
    earlybird: true,
  },
]

/** 개발 & IT 카테고리 2페이지 (Figma 14강) */
export const devItCoursesPage2: CategoryCourse[] = [
  {
    id: 'a11y',
    title: '시맨틱 마크업과 웹 접근성 실전 예제 프로젝트',
    author: '마크업장인 세아・38강・7시간',
    discount: 25,
    origin: 88000,
    final: 66000,
    rating: 4.7,
    reviews: 1540,
    thumb: '/figma/img/cat2-a11y.png',
    avatar: AV1,
    subcategory: '웹 퍼블리싱',
    earlybird: true,
  },
  {
    id: 'vue',
    title: 'Vue.js 입문부터 배포까지 한 번에 끝장내기',
    author: '뷰포인트 다온・64강・13시간',
    discount: 25,
    origin: 121000,
    final: 90750,
    rating: 4.6,
    reviews: 1320,
    thumb: '/figma/img/cat2-vue.png',
    avatar: AV2,
    subcategory: '프론트엔드',
    earlybird: true,
  },
  {
    id: 'spring',
    title: 'Spring Boot로 시작하는 백엔드 완전 정복',
    author: '스프링가든 호재・110강・22시간',
    discount: 40,
    origin: 187000,
    final: 112200,
    rating: 4.6,
    reviews: 1680,
    thumb: '/figma/img/cat2-spring.png',
    avatar: AV1,
    subcategory: '백엔드 & 서버',
    earlybird: true,
    event: true,
  },
  {
    id: 'rn',
    title: 'React Native 실전 모바일 개발 프로젝트 입문',
    author: '모바일덕후 한・68강・14시간',
    discount: 30,
    origin: 154000,
    final: 107800,
    rating: 4.6,
    reviews: 1390,
    thumb: '/figma/img/cat2-rn.png',
    avatar: AV2,
    subcategory: '모바일 & 앱 개발',
    earlybird: true,
  },
  {
    id: 'ml',
    title: '머신러닝 입문: 이론보다 실전 완벽 가이드',
    author: '모델링 오즈・80강・17시간',
    discount: 35,
    origin: 176000,
    final: 114400,
    rating: 4.6,
    reviews: 1840,
    thumb: '/figma/img/cat2-ml.png',
    avatar: AV1,
    subcategory: '데이터 & AI',
    earlybird: true,
  },
  {
    id: 'nocode-app',
    title: '노코드 앱 빌더로 만드는 나만의 서비스',
    author: '노코드연구소 제이・52강・11시간',
    discount: 35,
    origin: 121000,
    final: 78650,
    rating: 4.6,
    reviews: 1290,
    thumb: '/figma/img/cat2-nocode.png',
    avatar: AV2,
    subcategory: '노코드 & 자동화',
    earlybird: true,
    event: true,
  },
  {
    id: 'chatbot',
    title: '생성형 AI로 나만의 챗봇 만들기 프로젝트',
    author: '프롬프트연구소 리아・50강・10시간',
    discount: 25,
    origin: 143000,
    final: 107250,
    rating: 4.8,
    reviews: 2760,
    thumb: '/figma/img/cat2-chatbot.png',
    avatar: AV1,
    subcategory: 'AI 개발 도구',
    earlybird: true,
  },
  {
    id: 'rest-api',
    title: '실전 REST API & 데이터베이스 설계',
    author: '쿼리마스터 단・58강・12시간',
    discount: 30,
    origin: 132000,
    final: 92400,
    rating: 4.7,
    reviews: 1430,
    thumb: '/figma/img/cat2-rest.png',
    avatar: AV2,
    subcategory: '백엔드 & 서버',
    earlybird: true,
  },
  {
    id: 'typescript',
    title: 'TypeScript로 더 단단한 프론트엔드',
    author: '타입세이프 루크・48강・10시간',
    discount: 20,
    origin: 110000,
    final: 88000,
    rating: 4.7,
    reviews: 1510,
    thumb: '/figma/img/cat2-ts.png',
    avatar: AV1,
    subcategory: '프론트엔드',
    earlybird: true,
  },
  {
    id: 'sass',
    title: 'Sass와 반응형 컴포넌트 설계 마스터 클래스',
    author: '스타일러 진・33강・6시간',
    discount: 15,
    origin: 95000,
    final: 80750,
    rating: 4.6,
    reviews: 980,
    thumb: '/figma/img/cat2-sass.png',
    avatar: AV2,
    subcategory: '웹 퍼블리싱',
    earlybird: true,
  },
  {
    id: 'sql',
    title: 'SQL 데이터 분석 실무 프로젝트 완전 가이드',
    author: '쿼리마스터 단・42강・8시간 30분',
    discount: 20,
    origin: 88000,
    final: 70400,
    rating: 4.7,
    reviews: 2320,
    thumb: '/figma/img/cat2-sql.png',
    avatar: AV1,
    subcategory: '데이터 & AI',
    earlybird: true,
  },
  {
    id: 'swiftui',
    title: 'SwiftUI로 시작하는 iOS 앱 개발 완전 정복',
    author: '사과농장 지오・82강・17시간',
    discount: 20,
    origin: 176000,
    final: 140800,
    rating: 4.5,
    reviews: 980,
    thumb: '/figma/img/cat2-swift.png',
    avatar: AV2,
    subcategory: '모바일 & 앱 개발',
    earlybird: true,
  },
  {
    id: 'docker',
    title: 'Docker와 함께하는 배포 자동화 입문 교실',
    author: '데브옵스 료・40강・8시간',
    discount: 25,
    origin: 121000,
    final: 90750,
    rating: 4.5,
    reviews: 1120,
    thumb: '/figma/img/cat2-docker.png',
    avatar: AV1,
    subcategory: '백엔드 & 서버',
    earlybird: true,
  },
  {
    id: 'nextjs',
    title: 'Next.js로 완성하는 풀스택 웹앱 프로젝트 마스터 과정',
    author: '새벽코딩 제이든・95강・20시간',
    discount: 45,
    origin: 198000,
    final: 108900,
    rating: 4.8,
    reviews: 1890,
    thumb: '/figma/img/cat2-next.png',
    avatar: AV2,
    subcategory: '프론트엔드',
    earlybird: true,
    event: true,
  },
]

export const DEV_IT_TOTAL_PAGES = 2

export function getDevItCoursesByPage(page: number): CategoryCourse[] {
  if (page === 2) return devItCoursesPage2
  return devItCoursesPage1
}
