import type { Course } from './hootup-data'

export type CategoryCourse = Course & {
  subcategory: string
  earlybird?: boolean
  event?: boolean
}

/** Figma 커리어・머니 세부 카테고리 (node 154:14913) */
export const careerMoneySubcategories = [
  '전체',
  '직무역량 & 일잘러',
  '취업 & 이직',
  '마케팅 & 브랜딩',
  '사이드프로젝트 & N잡',
  '재테크 & 투자',
  '절세 & 머니 관리',
] as const

export type CareerMoneySubcategory = (typeof careerMoneySubcategories)[number]

/** 커리어 & 머니 카테고리 1페이지 (Figma 16강 · node 154:14908) */
export const careerMoneyCoursesPage1: CategoryCourse[] = [
  {
    id: 'cm-pm',
    title: '비전공자를 위한 서비스 기획·PM 입문',
    author: 'PM 도윤・64강・13시간',
    discount: 35,
    origin: 165000,
    final: 107250,
    rating: 4.8,
    reviews: 3640,
    thumb: '/figma/img/cm-pm.png',
    avatar: '/figma/img/cm-av-pm.png',
    subcategory: '직무역량 & 일잘러',
    earlybird: true,
  },
  {
    id: 'cm-insta',
    title: '0원으로 시작하는 인스타 콘텐츠 마케팅',
    author: '마케터 하루・50강・10시간',
    discount: 35,
    origin: 121000,
    final: 78650,
    rating: 4.8,
    reviews: 4210,
    thumb: '/figma/img/cm-insta.png',
    avatar: '/figma/img/cm-av-hari.png',
    subcategory: '마케팅 & 브랜딩',
    event: true,
  },
  {
    id: 'cm-side',
    title: '직장인 사이드프로젝트로 N잡 만드는 법',
    author: '사이드랩 민・48강・10시간',
    discount: 35,
    origin: 132000,
    final: 85800,
    rating: 4.8,
    reviews: 3870,
    thumb: '/figma/img/cm-side.png',
    avatar: '/figma/img/cm-av-min.png',
    subcategory: '사이드프로젝트 & N잡',
    event: true,
  },
  {
    id: 'cm-stock',
    title: '왕초보를 위한 주식·ETF 기초 이해하기 입문 과정',
    author: '머니노트 재이・40강・8시간',
    discount: 30,
    origin: 99000,
    final: 69300,
    rating: 4.7,
    reviews: 3280,
    thumb: '/figma/img/cm-stock.png',
    avatar: '/figma/img/cm-av-jay.png',
    subcategory: '재테크 & 투자',
    event: true,
  },
  {
    id: 'cm-content',
    title: '퇴근 후 2시간, 콘텐츠로 수익화하기 입문 과정',
    author: '사이드랩 민・44강・9시간',
    discount: 30,
    origin: 110000,
    final: 77000,
    rating: 4.7,
    reviews: 2960,
    thumb: '/figma/img/cm-content.png',
    avatar: '/figma/img/cm-av-min2.png',
    subcategory: '사이드프로젝트 & N잡',
    earlybird: true,
  },
  {
    id: 'cm-report',
    title: '한 번에 통과되는 실무 보고서·기획서 작성법',
    author: '문서장인 한결・42강・8시간',
    discount: 30,
    origin: 110000,
    final: 77000,
    rating: 4.7,
    reviews: 2480,
    thumb: '/figma/img/cm-report.png',
    avatar: '/figma/img/cm-av-han.png',
    subcategory: '직무역량 & 일잘러',
    event: true,
  },
  {
    id: 'cm-asset',
    title: '사회초년생을 위한 자산관리 방법 첫걸음',
    author: '가계부코치 린・34강・6시간 30분',
    discount: 20,
    origin: 88000,
    final: 70400,
    rating: 4.6,
    reviews: 1560,
    thumb: '/figma/img/cm-asset.png',
    avatar: '/figma/img/cm-av-rin.png',
    subcategory: '재테크 & 투자',
    earlybird: true,
  },
  {
    id: 'cm-copy',
    title: '클릭을 부르는 카피라이팅의 기술 중급 과정',
    author: '카피공방 윤슬・36강・7시간',
    discount: 30,
    origin: 99000,
    final: 69300,
    rating: 4.6,
    reviews: 1940,
    thumb: '/figma/img/cm-copy.png',
    avatar: '/figma/img/cm-av-yun.png',
    subcategory: '마케팅 & 브랜딩',
    earlybird: true,
  },
  {
    id: 'cm-startup',
    title: '혼자서도 시작하는 1인 창업 프로젝트 로드맵',
    author: '솔로창업 도이・56강・11시간',
    discount: 25,
    origin: 143000,
    final: 107250,
    rating: 4.6,
    reviews: 1510,
    thumb: '/figma/img/cm-startup.png',
    avatar: '/figma/img/cm-av-doi.png',
    subcategory: '사이드프로젝트 & N잡',
    event: true,
  },
  {
    id: 'cm-tax',
    title: '직장인이 꼭 알아야 할 절세·연말정산 가이드',
    author: '세무지기 한울・30강・6시간',
    discount: 25,
    origin: 99000,
    final: 74250,
    rating: 4.7,
    reviews: 2610,
    thumb: '/figma/img/cm-tax.png',
    avatar: '/figma/img/cm-av-hanul.png',
    subcategory: '절세 & 머니 관리',
    event: true,
  },
  {
    id: 'cm-decision',
    title: '숫자로 말하는 데이터 기반 의사결정',
    author: '데이터한입 수아・38강・7시간 30분',
    discount: 25,
    origin: 99000,
    final: 74250,
    rating: 4.6,
    reviews: 1560,
    thumb: '/figma/img/cm-decision.png',
    avatar: '/figma/img/cm-av-sua.png',
    subcategory: '직무역량 & 일잘러',
    earlybird: true,
  },
  {
    id: 'cm-perf',
    title: '데이터로 굴리는 퍼포먼스 마케팅 실전',
    author: '그로스해커 진・58강・12시간',
    discount: 40,
    origin: 154000,
    final: 92400,
    rating: 4.7,
    reviews: 2530,
    thumb: '/figma/img/cm-perf.png',
    avatar: '/figma/img/cm-av-jin.png',
    subcategory: '마케팅 & 브랜딩',
    event: true,
  },
  {
    id: 'cm-tools',
    title: '칼퇴를 부르는 업무 생산성 & 협업 도구',
    author: '일잘러 보나・46강・9시간',
    discount: 40,
    origin: 88000,
    final: 52800,
    rating: 4.7,
    reviews: 2910,
    thumb: '/figma/img/cm-tools.png',
    avatar: '/figma/img/cm-av-bona.png',
    subcategory: '직무역량 & 일잘러',
    event: true,
  },
  {
    id: 'cm-personal',
    title: '나를 브랜딩하는 퍼스널 브랜드 만들기',
    author: '브랜더 소을・40강・8시간',
    discount: 20,
    origin: 110000,
    final: 88000,
    rating: 4.6,
    reviews: 1430,
    thumb: '/figma/img/cm-personal.png',
    avatar: '/figma/img/cm-av-soeul.png',
    subcategory: '마케팅 & 브랜딩',
    earlybird: true,
  },
  {
    id: 'cm-store',
    title: '네이버 스마트스토어로 첫 매출 만들기',
    author: '셀러노트 가람・52강・10시간 30분',
    discount: 40,
    origin: 121000,
    final: 72600,
    rating: 4.7,
    reviews: 2540,
    thumb: '/figma/img/cm-store.png',
    avatar: '/figma/img/cm-av-garam.png',
    subcategory: '사이드프로젝트 & N잡',
    earlybird: true,
  },
  {
    id: 'cm-notion',
    title: '일 잘하는 직장러를 위한 노션 업무 정리법',
    author: '일잘러 보나・34강・6시간 30분',
    discount: 30,
    origin: 88000,
    final: 61600,
    rating: 4.6,
    reviews: 2130,
    thumb: '/figma/img/cm-notion.png',
    avatar: '/figma/img/cm-av-bona2.png',
    subcategory: '직무역량 & 일잘러',
    earlybird: true,
  },
]

/** 커리어 & 머니 카테고리 2페이지 (Figma 14강 · node 154:14961) */
export const careerMoneyCoursesPage2: CategoryCourse[] = [
  {
    id: 'cm2-resume',
    title: '합격을 부르는 자기소개서 & 이력서 작성',
    author: '커리어코치 단・36강・7시간',
    discount: 35,
    origin: 99000,
    final: 64350,
    rating: 4.7,
    reviews: 2760,
    thumb: '/figma/img/cm2-resume.png',
    avatar: '/figma/img/cm-av-pm.png',
    subcategory: '취업 & 이직',
    earlybird: true,
  },
  {
    id: 'cm2-seo',
    title: '검색되는 콘텐츠를 만드는 SEO & 블로그',
    author: '그로스해커 진・34강・7시간',
    discount: 30,
    origin: 99000,
    final: 69300,
    rating: 4.6,
    reviews: 1610,
    thumb: '/figma/img/cm2-seo.png',
    avatar: '/figma/img/cm-av-hari.png',
    subcategory: '마케팅 & 브랜딩',
    event: true,
  },
  {
    id: 'cm2-ebook',
    title: '전자책·디지털 상품으로 만드는 패시브 인컴',
    author: '솔로창업 도이・38강・7시간 30분',
    discount: 30,
    origin: 99000,
    final: 69300,
    rating: 4.6,
    reviews: 1820,
    thumb: '/figma/img/cm2-ebook.png',
    avatar: '/figma/img/cm-av-min.png',
    subcategory: '사이드프로젝트 & N잡',
    event: true,
  },
  {
    id: 'cm2-interview',
    title: '면접관의 마음을 여는 실전 면접 클래스',
    author: '커리어코치 단・32강・6시간 30분',
    discount: 30,
    origin: 99000,
    final: 69300,
    rating: 4.7,
    reviews: 2340,
    thumb: '/figma/img/cm2-interview.png',
    avatar: '/figma/img/cm-av-jay.png',
    subcategory: '취업 & 이직',
    event: true,
  },
  {
    id: 'cm2-estate',
    title: '처음 시작하는 사회 초년생을 위한 부동산 기초 이해',
    author: '부동산노트 한・36강・7시간 30분',
    discount: 25,
    origin: 99000,
    final: 74250,
    rating: 4.6,
    reviews: 1940,
    thumb: '/figma/img/cm2-estate.png',
    avatar: '/figma/img/cm-av-min2.png',
    subcategory: '재테크 & 투자',
    event: true,
  },
  {
    id: 'cm2-budget',
    title: '직장인을 위한 새는 돈을 막는 가계부 & 예산 관리',
    author: '가계부코치 린・28강・5시간 30분',
    discount: 20,
    origin: 77000,
    final: 61600,
    rating: 4.6,
    reviews: 1480,
    thumb: '/figma/img/cm2-budget.png',
    avatar: '/figma/img/cm-av-han.png',
    subcategory: '절세 & 머니 관리',
    earlybird: true,
  },
  {
    id: 'cm2-writing',
    title: '설득되는 보고를 만드는 비즈니스 글쓰기',
    author: '문서장인 한결・30강・6시간',
    discount: 20,
    origin: 88000,
    final: 70400,
    rating: 4.5,
    reviews: 1240,
    thumb: '/figma/img/cm2-writing.png',
    avatar: '/figma/img/cm-av-rin.png',
    subcategory: '직무역량 & 일잘러',
    event: true,
  },
  {
    id: 'cm2-career',
    title: '직무 전환을 위한 커리어 설계 로드맵',
    author: '커리어내비 윤・40강・8시간',
    discount: 25,
    origin: 110000,
    final: 82500,
    rating: 4.6,
    reviews: 1680,
    thumb: '/figma/img/cm2-career.png',
    avatar: '/figma/img/cm-av-yun.png',
    subcategory: '취업 & 이직',
    earlybird: true,
  },
  {
    id: 'cm2-youtube',
    title: '홍보가 필요한 사장님들을 위한 유튜브 채널 기획부터 성장까지',
    author: '마케터 하루・44강・9시간',
    discount: 25,
    origin: 110000,
    final: 82500,
    rating: 4.7,
    reviews: 2180,
    thumb: '/figma/img/cm2-youtube.png',
    avatar: '/figma/img/cm-av-doi.png',
    subcategory: '마케팅 & 브랜딩',
    earlybird: true,
  },
  {
    id: 'cm2-kmong',
    title: 'N잡러들을 위한 크몽·재능마켓으로 부업 시작하기',
    author: '셀러노트 가람・32강・6시간 30분',
    discount: 20,
    origin: 88000,
    final: 70400,
    rating: 4.5,
    reviews: 1270,
    thumb: '/figma/img/cm2-kmong.png',
    avatar: '/figma/img/cm-av-hanul.png',
    subcategory: '사이드프로젝트 & N잡',
    earlybird: true,
  },
  {
    id: 'cm2-itjob',
    title: '비전공자의 IT 직무 취업 전략 컨설팅',
    author: '커리어내비 윤・38강・8시간',
    discount: 40,
    origin: 121000,
    final: 72600,
    rating: 4.8,
    reviews: 3120,
    thumb: '/figma/img/cm2-itjob.png',
    avatar: '/figma/img/cm-av-sua.png',
    subcategory: '취업 & 이직',
    event: true,
  },
  {
    id: 'cm2-pension',
    title: '연금·ETF로 준비하는 장기 자산 설계',
    author: '머니노트 재이・32강・6시간 30분',
    discount: 30,
    origin: 99000,
    final: 69300,
    rating: 4.6,
    reviews: 1720,
    thumb: '/figma/img/cm2-pension.png',
    avatar: '/figma/img/cm-av-jin.png',
    subcategory: '재테크 & 투자',
    earlybird: true,
  },
  {
    id: 'cm2-linkedin',
    title: '링크드인으로 만드는 잘나가는 커리어 브랜딩',
    author: '브랜더 소을・28강・5시간 30분',
    discount: 20,
    origin: 88000,
    final: 70400,
    rating: 4.5,
    reviews: 1090,
    thumb: '/figma/img/cm2-linkedin.png',
    avatar: '/figma/img/cm-av-bona.png',
    subcategory: '취업 & 이직',
    earlybird: true,
  },
  {
    id: 'cm2-tax',
    title: '프리랜서·N잡러를 위한 세금 신고 가이드',
    author: '세무지기 한울・32강・6시간 30분',
    discount: 30,
    origin: 88000,
    final: 61600,
    rating: 4.6,
    reviews: 1300,
    thumb: '/figma/img/cm2-tax.png',
    avatar: '/figma/img/cm-av-soeul.png',
    subcategory: '절세 & 머니 관리',
    event: true,
  },
]

export const CAREER_MONEY_TOTAL_PAGES = 2

export const careerMoneySubcategoryRoutes: Partial<Record<CareerMoneySubcategory, string>> = {
  전체: '/category/career-money',
  '직무역량 & 일잘러': '/category/career-money/job-skills',
  '취업 & 이직': '/category/career-money/career',
  '마케팅 & 브랜딩': '/category/career-money/marketing',
  '사이드프로젝트 & N잡': '/category/career-money/side-project',
  '재테크 & 투자': '/category/career-money/finance',
  '절세 & 머니 관리': '/category/career-money/tax',
}

export function getCareerMoneyCoursesByPage(page: number): CategoryCourse[] {
  if (page === 2) return careerMoneyCoursesPage2
  return careerMoneyCoursesPage1
}

export function getAllCareerMoneyCourses(): CategoryCourse[] {
  return [...careerMoneyCoursesPage1, ...careerMoneyCoursesPage2]
}

export function getCareerMoneyCoursesBySubcategory(sub: CareerMoneySubcategory): CategoryCourse[] {
  if (sub === '전체') return getAllCareerMoneyCourses()
  return getAllCareerMoneyCourses().filter((c) => c.subcategory === sub)
}

export type CareerMoneyDeal = 'earlybird' | 'event'

export const careerMoneyDealRoutes: Record<CareerMoneyDeal, string> = {
  earlybird: '/category/career-money/earlybird',
  event: '/category/career-money/event',
}

export function getCareerMoneyCoursesByDeal(deal: CareerMoneyDeal): CategoryCourse[] {
  if (deal === 'earlybird') return getAllCareerMoneyCourses().filter((c) => c.earlybird)
  return getAllCareerMoneyCourses().filter((c) => c.event)
}

