import type { Course } from './hootup-data'

export type CategoryCourse = Course & {
  subcategory: string
  earlybird?: boolean
  event?: boolean
}

/** 시그니쳐 클래스 세부 필터 (대분류 기준) */
export const signatureClassesSubcategories = [
  '전체',
  '개발 & IT',
  '커리어 & 머니',
  '디자인 & 크리에이티브',
  '사진 & 영상',
  '드로잉 & 일러스트',
  '운동 & 마음챙김',
  '공예 & 핸드메이드',
  '요리 & 베이킹',
] as const

export type SignatureClassesSubcategory = (typeof signatureClassesSubcategories)[number]

/** 시그니쳐 클래스 1페이지 (16강) */
export const signatureClassesCoursesPage1: CategoryCourse[] = [
  {
    id: 'sig-webpub',
    title: '제로부터 완성하는 반응형 웹 퍼블리싱 마스터 클래스',
    author: '코드랩 현우・52강・11시간',
    discount: 30,
    origin: 110000,
    final: 77000,
    rating: 4.9,
    reviews: 4128,
    thumb: '/figma/img/cat-webpub.png',
    avatar: '/figma/img/avatar-1.png',
    subcategory: '개발 & IT',
    earlybird: true,
  },
  {
    id: 'sig-cm-pm',
    title: '비전공자를 위한 서비스 기획·PM 입문',
    author: 'PM 도윤・64강・13시간',
    discount: 35,
    origin: 165000,
    final: 107250,
    rating: 4.8,
    reviews: 3640,
    thumb: '/figma/img/cm-pm.png',
    avatar: '/figma/img/cm-av-pm.png',
    subcategory: '커리어 & 머니',
    earlybird: true,
  },
  {
    id: 'sig-dc-figma',
    title: '피그마로 완성하는 UX/UI 디자인 입문',
    author: '디자이너 서린・40강・9시간',
    discount: 35,
    origin: 132000,
    final: 85800,
    rating: 4.9,
    reviews: 3820,
    thumb: '/figma/img/dc-figma.png',
    avatar: '/figma/img/cm-av-pm.png',
    subcategory: '디자인 & 크리에이티브',
    earlybird: true,
  },
  {
    id: 'sig-pv-premiere',
    title: '어도비 프리미어 프로 브이로그 편집 A to Z',
    author: '에디터 한새・64강・13시간',
    discount: 40,
    origin: 143000,
    final: 85800,
    rating: 4.9,
    reviews: 3760,
    thumb: '/figma/img/pv-premiere.png',
    avatar: '/figma/img/pv-av-3.png',
    subcategory: '사진 & 영상',
    event: true,
  },
  {
    id: 'sig-di-ipad',
    title: '아이패드로 시작하는 감성 캐릭터 드로잉',
    author: '무지(MOOZI)・28강・6시간',
    discount: 35,
    origin: 99000,
    final: 64350,
    rating: 4.9,
    reviews: 4180,
    thumb: '/figma/img/di-ipad.png',
    avatar: '/figma/img/di-av-1.png',
    subcategory: '드로잉 & 일러스트',
    event: true,
  },
  {
    id: 'sig-fm-hometrain',
    title: '14일 홈트 챌린지: 코어부터 차근차근 다지기',
    author: '트레이너 강・28강・5시간',
    discount: 35,
    origin: 88000,
    final: 57200,
    rating: 4.8,
    reviews: 6240,
    thumb: '/figma/img/fm-hometrain.png',
    avatar: '/figma/img/fm-av-1.png',
    subcategory: '운동 & 마음챙김',
    earlybird: true,
  },
  {
    id: 'sig-ch-leather',
    title: '손끝에서 완성되는 첫 가죽 카드지갑 만들기',
    author: '레더공방 모루・30강・6시간',
    discount: 35,
    origin: 99000,
    final: 64350,
    rating: 4.8,
    reviews: 2340,
    thumb: '/figma/img/ch-leather.png',
    avatar: '/figma/img/ch-av-1.png',
    subcategory: '공예 & 핸드메이드',
    event: true,
  },
  {
    id: 'sig-cb-homecook',
    title: '자취생을 위한 실패 없는 한 끼 홈쿡 30',
    author: '키친노트 단・40강・8시간',
    discount: 35,
    origin: 88000,
    final: 57200,
    rating: 4.9,
    reviews: 5410,
    thumb: '/figma/img/cb-homecook.png',
    avatar: '/figma/img/cb-av-5.png',
    subcategory: '요리 & 베이킹',
    earlybird: true,
  },
  {
    id: 'sig-react',
    title: '포트폴리오까지 끝내는 React 프론트엔드 실전 프로젝트',
    author: '코드랩 현우・88강・18시간',
    discount: 40,
    origin: 165000,
    final: 99000,
    rating: 4.8,
    reviews: 2604,
    thumb: '/figma/img/cat-react.png',
    avatar: '/figma/img/avatar-1.png',
    subcategory: '개발 & IT',
    earlybird: true,
  },
  {
    id: 'sig-cm-perf',
    title: '데이터로 굴리는 퍼포먼스 마케팅 실전',
    author: '그로스해커 진・58강・12시간',
    discount: 40,
    origin: 154000,
    final: 92400,
    rating: 4.7,
    reviews: 2530,
    thumb: '/figma/img/cm-perf.png',
    avatar: '/figma/img/cm-av-jin.png',
    subcategory: '커리어 & 머니',
    event: true,
  },
  {
    id: 'sig-dc-logo',
    title: '나만의 감성을 담은 브랜드를 만드는 로고 디자인',
    author: '스튜디오 결・38강・8시간',
    discount: 35,
    origin: 154000,
    final: 100100,
    rating: 4.8,
    reviews: 2610,
    thumb: '/figma/img/dc-logo.png',
    avatar: '/figma/img/cm-av-min.png',
    subcategory: '디자인 & 크리에이티브',
    earlybird: true,
  },
  {
    id: 'sig-pv-smartphone',
    title: '스마트폰 하나로 인생샷 만드는 사진 클래스',
    author: '빛그림 윤도・42강・8시간',
    discount: 35,
    origin: 99000,
    final: 64350,
    rating: 4.8,
    reviews: 4920,
    thumb: '/figma/img/pv-smartphone.png',
    avatar: '/figma/img/pv-av-1.png',
    subcategory: '사진 & 영상',
    earlybird: true,
  },
  {
    id: 'sig-di-webtoon',
    title: '클립스튜디오 웹툰 작화 클래스 고급반',
    author: '작가 도담・52강・11시간',
    discount: 35,
    origin: 121000,
    final: 78650,
    rating: 4.7,
    reviews: 2060,
    thumb: '/figma/img/di-webtoon.png',
    avatar: '/figma/img/di-av-3.png',
    subcategory: '드로잉 & 일러스트',
    event: true,
  },
  {
    id: 'sig-fm-yoga',
    title: '뻣뻣한 몸이 풀리는 14일 모닝 요가 루틴',
    author: '요가하는 미오・30강・5시간 30분',
    discount: 35,
    origin: 88000,
    final: 57200,
    rating: 4.9,
    reviews: 3820,
    thumb: '/figma/img/fm-yoga.png',
    avatar: '/figma/img/fm-av-2.png',
    subcategory: '운동 & 마음챙김',
    event: true,
  },
  {
    id: 'sig-ch-handbuild',
    title: '손으로 빚는 나만의 그릇, 핸드빌딩 도예',
    author: '흙내음 도원・34강・7시간 30분',
    discount: 30,
    origin: 110000,
    final: 77000,
    rating: 4.8,
    reviews: 2010,
    thumb: '/figma/img/ch-handbuild.png',
    avatar: '/figma/img/ch-av-2.png',
    subcategory: '공예 & 핸드메이드',
    earlybird: true,
  },
  {
    id: 'sig-cb-baking',
    title: '아이들과 함께하는 실패 없는 홈베이킹 기초반',
    author: '베이커리 오븐・38강・7시간 30분',
    discount: 35,
    origin: 99000,
    final: 64350,
    rating: 4.8,
    reviews: 3320,
    thumb: '/figma/img/cb-baking.png',
    avatar: '/figma/img/cb-av-6.png',
    subcategory: '요리 & 베이킹',
    event: true,
  }
]

/** 시그니쳐 클래스 2페이지 (8강) */
export const signatureClassesCoursesPage2: CategoryCourse[] = [
  {
    id: 'sig-claude',
    title: '개발 생산성 10배 올리는 클로드 코드 마스터 과정',
    author: '새벽코딩 제이든・48강・10시간',
    discount: 30,
    origin: 154000,
    final: 107800,
    rating: 4.9,
    reviews: 3480,
    thumb: '/figma/img/cat-claude.png',
    avatar: '/figma/img/avatar-1.png',
    subcategory: '개발 & IT',
    event: true,
  },
  {
    id: 'sig-cm-side',
    title: '직장인 사이드프로젝트로 N잡 만드는 법',
    author: '사이드랩 민・48강・10시간',
    discount: 35,
    origin: 132000,
    final: 85800,
    rating: 4.8,
    reviews: 3890,
    thumb: '/figma/img/cm-side.png',
    avatar: '/figma/img/cm-av-min.png',
    subcategory: '커리어 & 머니',
    event: true,
  },
  {
    id: 'sig-dc-blender',
    title: '블렌더로 시작하는 첫 3D 모델링 마스터 클래스',
    author: '쓰리디랩 노아・52강・11시간',
    discount: 40,
    origin: 143000,
    final: 85800,
    rating: 4.8,
    reviews: 2740,
    thumb: '/figma/img/dc-blender.png',
    avatar: '/figma/img/cm-av-jay.png',
    subcategory: '디자인 & 크리에이티브',
    event: true,
  },
  {
    id: 'sig-pv-davinci',
    title: '다빈치 리졸브로 배우는 영상 색보정 입문',
    author: '컬러리스트 진・52강・11시간',
    discount: 35,
    origin: 132000,
    final: 85800,
    rating: 4.7,
    reviews: 1880,
    thumb: '/figma/img/pv-davinci.png',
    avatar: '/figma/img/pv-av-5.png',
    subcategory: '사진 & 영상',
    earlybird: true,
  },
  {
    id: 'sig-di-watercolor',
    title: '투명 수채화 입문, 빛을 담는 풍경 그리기 편',
    author: '수채연구소 윤・38강・7시간 30분',
    discount: 30,
    origin: 99000,
    final: 69300,
    rating: 4.8,
    reviews: 1860,
    thumb: '/figma/img/di-watercolor.png',
    avatar: '/figma/img/di-av-2.png',
    subcategory: '드로잉 & 일러스트',
    earlybird: true,
  },
  {
    id: 'sig-fm-sleep',
    title: '자기 전 5분, 잠이 깊어지는 수면 명상',
    author: '마인드풀 정・28강・4시간 30분',
    discount: 30,
    origin: 77000,
    final: 53900,
    rating: 4.8,
    reviews: 3460,
    thumb: '/figma/img/fm-sleep.png',
    avatar: '/figma/img/fm-av-4.png',
    subcategory: '운동 & 마음챙김',
    event: true,
  },
  {
    id: 'sig-ch-candle',
    title: '향으로 채우는 소이캔들 & 디퓨저 만들기 클래스',
    author: '센트랩・32강・6시간',
    discount: 35,
    origin: 88000,
    final: 57200,
    rating: 4.8,
    reviews: 2560,
    thumb: '/figma/img/ch-candle.png',
    avatar: '/figma/img/ch-av-3.png',
    subcategory: '공예 & 핸드메이드',
    event: true,
  },
  {
    id: 'sig-cb-coffee',
    title: '핸드드립부터 라떼아트까지, 커피의 기본',
    author: '바리스타 라온・40강・8시간',
    discount: 30,
    origin: 99000,
    final: 69300,
    rating: 4.7,
    reviews: 2210,
    thumb: '/figma/img/cb-coffee.png',
    avatar: '/figma/img/cb-av-1.png',
    subcategory: '요리 & 베이킹',
    event: true,
  }
]

export const SIGNATURE_CLASSES_TOTAL_PAGES = 2

export const signatureClassesSubcategoryRoutes: Partial<Record<SignatureClassesSubcategory, string>> = {
  전체: '/category/signature-classes',
}

export function getSignatureClassesCoursesByPage(page: number): CategoryCourse[] {
  if (page === 2) return signatureClassesCoursesPage2
  return signatureClassesCoursesPage1
}

export function getAllSignatureClassesCourses(): CategoryCourse[] {
  return [...signatureClassesCoursesPage1, ...signatureClassesCoursesPage2]
}

export function getSignatureClassesCoursesBySubcategory(
  sub: SignatureClassesSubcategory,
): CategoryCourse[] {
  if (sub === '전체') return getAllSignatureClassesCourses()
  return getAllSignatureClassesCourses().filter((c) => c.subcategory === sub)
}


export type SignatureClassesDeal = 'earlybird' | 'event'

export const signatureClassesDealRoutes: Record<SignatureClassesDeal, string> = {
  earlybird: '/category/signature-classes/earlybird',
  event: '/category/signature-classes/event',
}

export function getSignatureClassesCoursesByDeal(deal: SignatureClassesDeal): CategoryCourse[] {
  if (deal === 'earlybird') return getAllSignatureClassesCourses().filter((c) => c.earlybird)
  return getAllSignatureClassesCourses().filter((c) => c.event)
}
