export const magazineCategories = [
  '전체',
  'Development & IT',
  'Career & Money',
  'Design',
  'Drawing',
  'Photo & Video',
  'Fitness',
  'Craft',
  'Cooking',
] as const

export const magazineCover = {
  badge: 'COVER STORY',
  category: 'DEVELOPMENT & IT',
  title: '비전공자가 6개월 만에 웹 퍼블리셔로 취업한 진짜 순서',
  excerpt:
    '퇴근 후 두 시간, 그리고 순서 하나. 첫 달의 기본기부터 면접에서 받은 질문까지, 곁에서 지켜본 6개월의 진짜 순서를 단계별로 풀었습니다.',
  author: '코드랩 현우',
  meta: 'June 13 · 12분 읽기 · 댓글 19',
  thumb: '/figma/magazine/cover-hello.png',
  avatar: '/figma/magazine/av-hyunwoo.png',
  href: '#',
}

export const magazineClasses = [
  {
    id: 'webpub',
    href: '/course/responsive-publishing',
    thumb: '/figma/magazine/class-webpub.png',
    thumbAlt: '여러 화면 크기로 반응형 레이아웃을 확인하는 웹 퍼블리싱 작업 화면',
    flags: [
      { label: 'SIGNATURE', tone: 'signature' as const },
      { label: 'BEST', tone: 'best' as const },
    ],
    discountBadge: '30% 할인',
    title: '제로부터 완성하는 반응형 웹 퍼블리싱 마스터 클래스',
    meta: '코드랩 현우・52강・11시간',
    rate: '30%',
    origin: '110,000원',
    price: '77,000원',
    rating: '4.9',
    stars: '/figma/course-detail/stars-49.svg',
    students: '4,128명 수강',
    avatar: '/figma/magazine/av-hyunwoo.png',
  },
  {
    id: 'css',
    href: '/course/responsive-publishing',
    thumb: '/figma/magazine/class-css.png',
    thumbAlt: 'CSS Flexbox와 Grid 레이아웃 강의 썸네일',
    flags: [] as { label: string; tone: 'signature' | 'best' }[],
    discountBadge: '40% 할인',
    title: 'CSS Flex & Grid 레이아웃 완전 정복',
    meta: '코드랩 현우・44강・8시간 30분',
    rate: '40%',
    origin: '99,000원',
    price: '59,400원',
    rating: '4.9',
    stars: '/figma/course-detail/stars-49.svg',
    students: '3,210명 수강',
    avatar: '/figma/magazine/av-hyunwoo.png',
  },
  {
    id: 'vanilla',
    href: '/course/responsive-publishing',
    thumb: '/figma/magazine/class-vanilla.png',
    thumbAlt: '바닐라 자바스크립트로 만드는 인터랙티브 웹 강의 썸네일',
    flags: [] as { label: string; tone: 'signature' | 'best' }[],
    discountBadge: '30% 할인',
    title: '바닐라 자바 스크립트로 만드는 인터랙티브 웹',
    meta: '코드랩 현우・56강・12시간',
    rate: '30%',
    origin: '143,000원',
    price: '100,100원',
    rating: '4.7',
    stars: '/figma/course-detail/stars-47.svg',
    students: '2,180명 수강',
    avatar: '/figma/magazine/av-hyunwoo.png',
  },
]

export const magazinePicks = [
  {
    id: 'drawing',
    category: 'DRAWING',
    title: '그림 똥손도 21일이면 달라진다, 매일 10분 드로잉의 힘',
    excerpt:
      '재능보다 습관, 3주 만에 내 캐릭터 그리기. 하루 10분 선 긋기부터 시작한 사람들의 진짜 변화를 모았어요.',
    author: '끄적이는 밤',
    meta: 'June 13 · 댓글 19',
    thumb: '/figma/magazine/pick-drawing.png',
    avatar: '/figma/magazine/av-scribble.png',
    href: '#',
  },
  {
    id: 'money',
    category: 'CAREER & MONEY',
    title: '퇴근 후 2시간, N잡으로 첫 수익을 만든 사람들의 공통점',
    excerpt:
      '가진 기술 하나로 시작한 평범한 직장인들의 사이드 이야기. 첫 수익까지 걸린 시간과 흔한 착각을 정리했어요.',
    author: '사이드랩 민',
    meta: 'June 13 · 댓글 19',
    thumb: '/figma/magazine/pick-money.png',
    avatar: '/figma/magazine/av-sidelab.png',
    href: '#',
  },
]

export const magazineRecent = [
  {
    id: 'insta',
    category: 'CAREER & MONEY',
    title: '0원으로 시작하는 인스타 마케팅, 뭐부터 할까',
    excerpt: '팔로워 0에서 첫 고객까지, 돈 안 드는 콘텐츠 전략.',
    meta: '마케터 하루 · June 25 · 댓글 27',
    thumb: '/figma/magazine/recent-insta.png',
    href: '#',
  },
  {
    id: 'figma',
    category: 'DESIGN',
    title: '피그마, 오토레이아웃만 알아도 인생이 편해져요',
    excerpt: '반응형 화면을 자동으로 정렬하는 디자이너의 필수기.',
    meta: '디자이너 서린 · June 18 · 댓글 22',
    thumb: '/figma/magazine/recent-figma.png',
    href: '#',
  },
  {
    id: 'cooking',
    category: 'COOKING',
    title: '자취 요리, 실패 없는 한 끼 30선',
    excerpt: '재료 몇 개로 뚝딱, 오늘 저녁 걱정 끝.',
    meta: '키친노트 단 · June 17 · 댓글 24',
    thumb: '/figma/magazine/recent-cooking.png',
    href: '#',
  },
  {
    id: 'fitness',
    category: 'FITNESS',
    title: '작심삼일 홈트, 딱 14일만 버텨보기',
    excerpt: '코어부터 차근차근, 집에서 만드는 운동 습관.',
    meta: '트레이너 강 · June 16 · 댓글 26',
    thumb: '/figma/magazine/recent-fitness.png',
    href: '#',
  },
  {
    id: 'photo',
    category: 'PHOTO & VIDEO',
    title: '스마트폰으로 인생샷 찍는 사람들의 비밀',
    excerpt: '장비 탓 그만, 오늘부터 달라지는 구도와 빛 읽기.',
    meta: '빛그림 윤도 · June 15 · 댓글 25',
    thumb: '/figma/magazine/recent-photo.png',
    href: '#',
  },
  {
    id: 'craft',
    category: 'CRAFT',
    title: '첫 가죽 공예, 카드지갑부터 만들어봐요',
    excerpt: '손끝에서 완성되는 나만의 가죽 소품 시작기.',
    meta: '레더공방 모루 · June 14 · 댓글 17',
    thumb: '/figma/magazine/recent-craft.png',
    href: '#',
  },
]

export const magazineArchive = [
  {
    id: '10',
    no: '10',
    category: 'DRAWING',
    title: '수채화, 물 조절만 알면 절반은 성공',
    meta: '수채연구소 윤 · May 29',
    href: '#',
  },
  {
    id: '11',
    no: '11',
    category: 'COOKING',
    title: '비건 한 끼, 맛있게 건강해지는 법',
    meta: '채식테이블 보리 · May 28',
    href: '#',
  },
  {
    id: '12',
    no: '12',
    category: 'CRAFT',
    title: '흙을 빚는 시간이 주는 몰입',
    meta: '흙내음 도원 · May 26',
    href: '#',
  },
]
