import type { Course } from './hootup-data'

export type CategoryCourse = Course & {
  subcategory: string
  earlybird?: boolean
  event?: boolean
}

/** Figma 디자인・크리에이티브 세부 카테고리 (node 154:14860) */
export const designCreativeSubcategories = [
  '전체',
  'UX/UI 디자인',
  '그래픽 디자인',
  '브랜딩 & 로고',
  '3D & 모션 디자인',
  '일러스트 & 디지털아트',
  '크리에이티브 입문',
] as const

export type DesignCreativeSubcategory = (typeof designCreativeSubcategories)[number]

/** 디자인 & 크리에이티브 1페이지 (Figma 16강 · node 154:14855) */
export const designCreativeCoursesPage1: CategoryCourse[] = [
  {
    id: 'dc-figma',
    title: '피그마로 완성하는 UX/UI 디자인 입문',
    author: '디자이너 서린・40강・9시간',
    discount: 35,
    origin: 132000,
    final: 85800,
    rating: 4.9,
    reviews: 3820,
    thumb: '/figma/img/dc-figma.png',
    avatar: '/figma/img/cm-av-pm.png',
    subcategory: 'UX/UI 디자인',
    earlybird: true,
  },
  {
    id: 'dc-ps',
    title: '포토샵 누끼부터 합성까지 한 번에 마스터 클래스',
    author: '리터처 오・44강・9시간',
    discount: 35,
    origin: 99000,
    final: 64350,
    rating: 4.8,
    reviews: 3540,
    thumb: '/figma/img/dc-ps.png',
    avatar: '/figma/img/cm-av-hari.png',
    subcategory: '그래픽 디자인',
    earlybird: true,
    event: true,
  },
  {
    id: 'dc-logo',
    title: '나만의 감성을 담은 브랜드를 만드는 로고 디자인',
    author: '스튜디오 결・38강・8시간',
    discount: 35,
    origin: 154000,
    final: 100100,
    rating: 4.8,
    reviews: 2610,
    thumb: '/figma/img/dc-logo.png',
    avatar: '/figma/img/cm-av-min.png',
    subcategory: '브랜딩 & 로고',
    earlybird: true,
  },
  {
    id: 'dc-blender',
    title: '블렌더로 시작하는 첫 3D 모델링 마스터 클래스',
    author: '쓰리디랩 노아・52강・11시간',
    discount: 40,
    origin: 143000,
    final: 85800,
    rating: 4.8,
    reviews: 2740,
    thumb: '/figma/img/dc-blender.png',
    avatar: '/figma/img/cm-av-jay.png',
    subcategory: '3D & 모션 디자인',
    earlybird: true,
    event: true,
  },
  {
    id: 'dc-concept',
    title: '디지털 페인팅으로 그리는 컨셉아트 입문',
    author: '그림창고 보리・46강・10시간',
    discount: 30,
    origin: 121000,
    final: 84700,
    rating: 4.7,
    reviews: 2040,
    thumb: '/figma/img/dc-concept.png',
    avatar: '/figma/img/cm-av-min2.png',
    subcategory: '일러스트 & 디지털아트',
    earlybird: true,
  },
  {
    id: 'dc-uxsys',
    title: '실무로 가는 UX/UI: 디자인 시스템과 프로토타이핑',
    author: '디자이너 서린・56강・12시간',
    discount: 40,
    origin: 165000,
    final: 99000,
    rating: 4.8,
    reviews: 2470,
    thumb: '/figma/img/dc-uxsys.png',
    avatar: '/figma/img/cm-av-han.png',
    subcategory: 'UX/UI 디자인',
    earlybird: true,
    event: true,
  },
  {
    id: 'dc-vector',
    title: '일러스트레이터로 시작하는 벡터 그래픽',
    author: '벡터공방 단・40강・8시간',
    discount: 30,
    origin: 110000,
    final: 77000,
    rating: 4.7,
    reviews: 1980,
    thumb: '/figma/img/dc-vector.png',
    avatar: '/figma/img/cm-av-rin.png',
    subcategory: '그래픽 디자인',
    earlybird: true,
  },
  {
    id: 'dc-identity',
    title: '무드보드부터 컬러까지, 브랜드 아이덴티티 설계',
    author: '스튜디오 결・34강・7시간',
    discount: 20,
    origin: 121000,
    final: 96800,
    rating: 4.6,
    reviews: 1470,
    thumb: '/figma/img/dc-identity.png',
    avatar: '/figma/img/cm-av-yun.png',
    subcategory: '브랜딩 & 로고',
    earlybird: true,
  },
  {
    id: 'dc-ae',
    title: '애프터이펙트 모션그래픽 디자인 실전',
    author: '모션랩 케이・48강・10시간',
    discount: 35,
    origin: 132000,
    final: 85800,
    rating: 4.7,
    reviews: 2120,
    thumb: '/figma/img/dc-ae.png',
    avatar: '/figma/img/cm-av-doi.png',
    subcategory: '3D & 모션 디자인',
    earlybird: true,
  },
  {
    id: 'dc-bg',
    title: '분위기를 만드는 배경 일러스트 & 라이팅',
    author: '빛담은 노을・40강・8시간 30분',
    discount: 20,
    origin: 110000,
    final: 88000,
    rating: 4.6,
    reviews: 1090,
    thumb: '/figma/img/dc-bg.png',
    avatar: '/figma/img/cm-av-hanul.png',
    subcategory: '일러스트 & 디지털아트',
    earlybird: true,
  },
  {
    id: 'dc-color',
    title: '주니어 디자이너를 위한 컬러와 레이아웃 감각 키우기',
    author: '디자인첫걸음 유・28강・5시간 30분',
    discount: 20,
    origin: 77000,
    final: 61600,
    rating: 4.6,
    reviews: 1620,
    thumb: '/figma/img/dc-color.png',
    avatar: '/figma/img/cm-av-sua.png',
    subcategory: '크리에이티브 입문',
    earlybird: true,
  },
  {
    id: 'dc-research',
    title: '데이터로 설득하는 UX 리서치 입문 클래스',
    author: '리서처 다인・38강・8시간',
    discount: 25,
    origin: 121000,
    final: 90750,
    rating: 4.6,
    reviews: 1120,
    thumb: '/figma/img/dc-research.png',
    avatar: '/figma/img/cm-av-jin.png',
    subcategory: 'UX/UI 디자인',
    earlybird: true,
  },
  {
    id: 'dc-basic',
    title: '비전공자를 위한 디자인 기초와 감각 키우기',
    author: '디자인첫걸음 유・30강・6시간',
    discount: 25,
    origin: 88000,
    final: 66000,
    rating: 4.8,
    reviews: 3180,
    thumb: '/figma/img/dc-basic.png',
    avatar: '/figma/img/cm-av-bona.png',
    subcategory: '크리에이티브 입문',
    earlybird: true,
  },
  {
    id: 'dc-typo',
    title: '보는 사람을 사로잡는 편집 & 타이포그래피',
    author: '레이아웃 제이・36강・7시간 30분',
    discount: 25,
    origin: 99000,
    final: 74250,
    rating: 4.6,
    reviews: 1340,
    thumb: '/figma/img/dc-typo.png',
    avatar: '/figma/img/cm-av-soeul.png',
    subcategory: '그래픽 디자인',
    earlybird: true,
  },
  {
    id: 'dc-selfbrand',
    title: '작은 가게를 위한 스텝바이스텝 셀프 브랜딩 키트',
    author: '브랜더 소을・30강・6시간',
    discount: 30,
    origin: 99000,
    final: 69300,
    rating: 4.7,
    reviews: 1820,
    thumb: '/figma/img/dc-selfbrand.png',
    avatar: '/figma/img/cm-av-garam.png',
    subcategory: '브랜딩 & 로고',
    earlybird: true,
  },
  {
    id: 'dc-render',
    title: '블렌더 3D 제품 렌더링 & 비주얼 포트폴리오 프로젝트',
    author: '쓰리디랩 노아・44강・9시간 30분',
    discount: 25,
    origin: 132000,
    final: 99000,
    rating: 4.6,
    reviews: 1150,
    thumb: '/figma/img/dc-render.png',
    avatar: '/figma/img/cm-av-bona2.png',
    subcategory: '3D & 모션 디자인',
    earlybird: true,
  },
]

/** 디자인 & 크리에이티브 2페이지 (Figma 14강 · node 154:15296) */
export const designCreativeCoursesPage2: CategoryCourse[] = [
  {
    id: 'dc2-char',
    title: '게임 캐릭터 컨셉아트 디자인 포트폴리오 프로젝트',
    author: '그림창고 보리・50강・11시간',
    discount: 35,
    origin: 143000,
    final: 92950,
    rating: 4.7,
    reviews: 1680,
    thumb: '/figma/img/dc2-char.png',
    avatar: '/figma/img/cm-av-pm.png',
    subcategory: '일러스트 & 디지털아트',
    earlybird: true,
  },
  {
    id: 'dc2-uiport',
    title: '대학생들을 위한 UI 디자인 포트폴리오 처음 만들기',
    author: '디자인첫걸음 유・34강・7시간',
    discount: 30,
    origin: 88000,
    final: 61600,
    rating: 4.7,
    reviews: 2050,
    thumb: '/figma/img/dc2-uiport.png',
    avatar: '/figma/img/cm-av-hari.png',
    subcategory: '크리에이티브 입문',
    earlybird: true,
  },
  {
    id: 'dc2-mobile',
    title: '모바일 앱 UI 디자인 실전 예제 프로젝트',
    author: '프로덕트 한별・48강・10시간',
    discount: 30,
    origin: 143000,
    final: 100100,
    rating: 4.7,
    reviews: 1640,
    thumb: '/figma/img/dc2-mobile.png',
    avatar: '/figma/img/cm-av-min.png',
    subcategory: 'UX/UI 디자인',
    earlybird: true,
  },
  {
    id: 'dc2-indesign',
    title: '인디자인으로 만드는 편집 디자인 포트폴리오 완성반',
    author: '레이아웃 제이・38강・8시간',
    discount: 20,
    origin: 99000,
    final: 79200,
    rating: 4.5,
    reviews: 890,
    thumb: '/figma/img/dc2-indesign.png',
    avatar: '/figma/img/cm-av-jay.png',
    subcategory: '그래픽 디자인',
    earlybird: true,
  },
  {
    id: 'dc2-package',
    title: '패키지 & 굿즈 디자인 실전 포트폴리오',
    author: '스튜디오 결・36강・7시간 30분',
    discount: 25,
    origin: 121000,
    final: 90750,
    rating: 4.6,
    reviews: 1180,
    thumb: '/figma/img/dc2-package.png',
    avatar: '/figma/img/cm-av-min2.png',
    subcategory: '브랜딩 & 로고',
    earlybird: true,
  },
  {
    id: 'dc2-motionlogo',
    title: '로고가 살아 움직이는 모션 로고 제작 프로젝트',
    author: '모션랩 케이・34강・7시간',
    discount: 30,
    origin: 110000,
    final: 77000,
    rating: 4.6,
    reviews: 1390,
    thumb: '/figma/img/dc2-motionlogo.png',
    avatar: '/figma/img/cm-av-han.png',
    subcategory: '3D & 모션 디자인',
    earlybird: true,
  },
  {
    id: 'dc2-coloring',
    title: '포토샵 디지털 일러스트 채색 마스터 클래스',
    author: '빛담은 노을・42강・9시간',
    discount: 30,
    origin: 110000,
    final: 77000,
    rating: 4.6,
    reviews: 1420,
    thumb: '/figma/img/dc2-coloring.png',
    avatar: '/figma/img/cm-av-rin.png',
    subcategory: '일러스트 & 디지털아트',
    earlybird: true,
  },
  {
    id: 'dc2-landing',
    title: '웹사이트 UI 디자인: 랜딩페이지부터',
    author: '프로덕트 한별・44강・9시간',
    discount: 25,
    origin: 121000,
    final: 90750,
    rating: 4.6,
    reviews: 1380,
    thumb: '/figma/img/dc2-landing.png',
    avatar: '/figma/img/cm-av-yun.png',
    subcategory: 'UX/UI 디자인',
    earlybird: true,
  },
  {
    id: 'dc2-sns',
    title: '자영업자를 위한 카드뉴스 & SNS 콘텐츠 디자인',
    author: '콘텐츠공방 라라・30강・6시간',
    discount: 35,
    origin: 88000,
    final: 57200,
    rating: 4.7,
    reviews: 2460,
    thumb: '/figma/img/dc2-sns.png',
    avatar: '/figma/img/cm-av-doi.png',
    subcategory: '그래픽 디자인',
    earlybird: true,
    event: true,
  },
  {
    id: 'dc2-naming',
    title: '디자이너 브랜드를 위한 브랜드 슬로건 & 네이밍 워크숍',
    author: '카피공방 윤슬・28강・5시간 30분',
    discount: 20,
    origin: 88000,
    final: 70400,
    rating: 4.5,
    reviews: 860,
    thumb: '/figma/img/dc2-naming.png',
    avatar: '/figma/img/cm-av-hanul.png',
    subcategory: '브랜딩 & 로고',
    earlybird: true,
  },
  {
    id: 'dc2-c4d',
    title: '시네마4D로 만드는 3D 타이포그래피',
    author: '쓰리디랩 노아・40강・8시간 30분',
    discount: 20,
    origin: 132000,
    final: 105600,
    rating: 4.5,
    reviews: 780,
    thumb: '/figma/img/dc2-c4d.png',
    avatar: '/figma/img/cm-av-sua.png',
    subcategory: '3D & 모션 디자인',
    earlybird: true,
  },
  {
    id: 'dc2-emoji',
    title: '감성 굿즈를 부르는 이모티콘 일러스트',
    author: '무지(MOOZI)・32강・6시간 30분',
    discount: 25,
    origin: 88000,
    final: 66000,
    rating: 4.8,
    reviews: 3260,
    thumb: '/figma/img/dc2-emoji.png',
    avatar: '/figma/img/cm-av-jin.png',
    subcategory: '일러스트 & 디지털아트',
    earlybird: true,
  },
  {
    id: 'dc2-job',
    title: '디자인 포트폴리오로 UX/UI 취업하기',
    author: '디자이너 서린・36강・8시간',
    discount: 40,
    origin: 121000,
    final: 72600,
    rating: 4.8,
    reviews: 2180,
    thumb: '/figma/img/dc2-job.png',
    avatar: '/figma/img/cm-av-bona.png',
    subcategory: 'UX/UI 디자인',
    earlybird: true,
    event: true,
  },
  {
    id: 'dc2-retouch',
    title: '팔로워를 부르는 포토샵 감성 보정 & 합성 아트',
    author: '리터처 오・34강・7시간',
    discount: 30,
    origin: 99000,
    final: 69300,
    rating: 4.6,
    reviews: 1720,
    thumb: '/figma/img/dc2-retouch.png',
    avatar: '/figma/img/cm-av-soeul.png',
    subcategory: '그래픽 디자인',
    earlybird: true,
  },
]

export const DESIGN_CREATIVE_TOTAL_PAGES = 2

export const designCreativeSubcategoryRoutes: Partial<Record<DesignCreativeSubcategory, string>> = {
  전체: '/category/design-creative',
  'UX/UI 디자인': '/category/design-creative/ux-ui',
  '그래픽 디자인': '/category/design-creative/graphic',
  '브랜딩 & 로고': '/category/design-creative/branding',
  '3D & 모션 디자인': '/category/design-creative/motion',
}

export function getDesignCreativeCoursesByPage(page: number): CategoryCourse[] {
  if (page === 2) return designCreativeCoursesPage2
  return designCreativeCoursesPage1
}

export function getAllDesignCreativeCourses(): CategoryCourse[] {
  return [...designCreativeCoursesPage1, ...designCreativeCoursesPage2]
}

export function getDesignCreativeCoursesBySubcategory(
  sub: DesignCreativeSubcategory,
): CategoryCourse[] {
  if (sub === '전체') return getAllDesignCreativeCourses()
  return getAllDesignCreativeCourses().filter((c) => c.subcategory === sub)
}
